services:
  db:
    build:
      context: ./Mosifra-API/.
      dockerfile: dockerfile_postgres
    container_name: mosifra_db
    environment:
      POSTGRES_DB: sae_db
      POSTGRES_USER: sae_user
      POSTGRES_PASSWORD: sae_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Mosifra-API/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:7
    container_name: mosifra_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./Mosifra-API/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: file_metadata

  minio:
    image: minio/minio:latest
    container_name: mosifra_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mosifra
      MINIO_ROOT_PASSWORD: mosifra123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console Web
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    container_name: mosifra_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./Mosifra-API/.
    container_name: mosifra_api
    depends_on:
      - db
      - mongo
      - minio
      - redis
    environment:
      DATABASE_URL: postgres://sae_user:sae_password@db:5432/sae_db
      MONGO_URL: mongodb://mongo:27017/file_metadata
      JWT_SECRET: ${JWT_SECRET}
      API_PORT: ${API_PORT}
      ROCKET_SECRET: ${ROCKET_SECRET}

      # MinIO / S3
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: mosifra
      S3_SECRET_KEY: mosifra123
      S3_BUCKET: documents

      # Redis
      REDIS_URL: redis://:redis_password@redis:6379/0
    ports:
      - "8010:8000"

  front:
    build: ./Mosifra-Front/.
    container_name: mosifra_front
    depends_on:
      - db
      - api
    environment:
      API_URL: ${API_ROOT}:${API_PORT}
    ports:
      - "8070:8080"

volumes:
  db_data:
  mongo_data:
  minio_data:
  redis_data:
